version: "3.3"
services:
  php:
    build:
      context: .
      dockerfile: ./data/dockerfile
    restart: always
    ports:
     - "9000:9000"
    volumes:
     - .:/var/www/test
    networks:
     - app_network
    depends_on:
     - postgres
  web:
    image: nginx
    restart: always
    ports:
     - "80:80"
    volumes:
     - .:/var/www/test
     - ./data/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
     - app_network
    depends_on:
     - php
  postgres:
    image: postgres
    restart: always
    ports:
     - "5436:5436"
    volumes:
     - ./data/postgres/:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: test
    networks:
     - app_network
networks:
  app_network:
    driver: bridge
    
