FROM php:8.0-fpm
WORKDIR /var/www/test
RUN apt-get update \
    && apt-get install -y \
                          libzip-dev \
                          zip                        
RUN docker-php-ext-install bcmath \
    && docker-php-ext-install zip    
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
